
CFLAGS_KERNEL	+= -I$(srctree)/arch/mips/xburst/soc-m200/chip-m200/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)

obj-y		+= common/
obj-$(CONFIG_WATCH_NEWTON2)		+= $(CONFIG_BOARD_NAME)/
obj-$(CONFIG_WATCH_AW808)		+= $(CONFIG_BOARD_NAME)/
