obj-$(CONFIG_SLPT) += slpt.o slpt_res.o slpt_key.o slpt_misc.o slpt_map.o slpt_cache.o \
                      malloc_with_name.o argv_creator.o \
                      slpt_method.o slpt_ioctl.o \
                      slpt_power_state.o
